//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CameraDatabase.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Camera
    {
        //No validation requiered
        public int Id { get; set; }

        [StringLength(20, MinimumLength = 2)]
        [Required]
        public string Manufacturer { get; set; }

        [StringLength(20, MinimumLength = 1)]
        [Required]
        public string Model { get; set; }

        [StringLength(10, MinimumLength = 3)]
        [Required]
        public string Style { get; set; }

        [Range(0, 10000)]
        [Required]
        public decimal Megapixels { get; set; }

        [StringLength(50, MinimumLength = 3)]
        [Required]
        public string Sensor { get; set; }

        [StringLength(20, MinimumLength = 2)]
        [Required]
        public string ISO { get; set; }

        [StringLength(50, MinimumLength = 3)]
        [Required]
        public string Shutter { get; set; }

        [Range(0, 1000)]
        [Required]
        public int FocusingPoints { get; set; }

        [StringLength(50, MinimumLength = 3)]
        [Required]
        public string Processor { get; set; }

        [StringLength(50, MinimumLength = 3)]
        [Required]
        public string Flash { get; set; }

        [StringLength(200, MinimumLength = 3)]
        [Required]
        public string Memory { get; set; }

        [StringLength(50, MinimumLength = 3)]
        [Required]
        public string Interface { get; set; }

        [StringLength(50, MinimumLength = 3)]
        [Required]
        public string Battery { get; set; }

        [StringLength(50, MinimumLength = 3)]
        [Required]
        public string Dimensions { get; set; }

        [Range(0, 10000)]
        public Nullable<int> Weight { get; set; }

        [Range(0, 100000)]
        [DataType(DataType.Currency)]
        public Nullable<decimal> Price { get; set; }

        public string Image { get; set; }

        public string SampleImage { get; set; }

        public int Rate { get; set; }
    }
}
